version: "3.8"

services:
  mysql:
    image: 'mysql:8.0.34'
    container_name: wanted_db
    restart: always
    environment:
      - 'MYSQL_DATABASE=wanted'
      - 'MYSQL_PASSWORD=password'
      - 'MYSQL_ROOT_PASSWORD=rootpassword'
      - 'MYSQL_USER=limvik'
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - '33306:3306'
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: wanted_app
    develop:
      watch:
        - action: rebuild
          path: ./build/libs
    depends_on:
      mysql:
        condition: service_started
    ports:
      - '9001:9001'
  adminer:
    image: adminer
    restart: always
    ports:
      - '8081:8080'