openapi: 3.1.0
info:
  title: Wanted pre onboarding backend
  description: |-
    [원티드 백엔드 프리온보딩 인턴십 과제 페이지](https://bow-hair-db3.notion.site/1850bca26fda4e0ca1410df270c03409)의 요구사항에 맞추어 설계한 API 입니다.

    관련 링크:
    - [원티드 백엔드 프리온보딩 인턴십 10월](https://www.wanted.co.kr/events/pre_ob_be_7)

  contact:
    email: seongguk.dev@gmail.com
    name: 정성국
    url: https://limvik.github.io
  license:
    name: MIT License
    url: https://github.com/limvik/wanted-pre-onboarding-backend/blob/main/LICENSE
  version: 0.0.1
servers:
  - url: "{protocol}://{hostname}/api/v1"
    variables:
      hostname:
        default: localhost:8080
      protocol:
        default: http
tags:
  - name: Post
    description: 회사(Company)가 관리하는 채용공고
  - name: Application
    description: 사용자(User)의 채용공고 지원내역(Application)
paths:
  /posts:
    get:
      tags:
        - Post
      summary: 채용공고 목록을 가져옵니다.
      description: |-
        전체 채용공고 목록의 일부를 가져옵니다. 회사 이름, 채용포지션, 스킬 등에 포함된 키워드로 검색할 수 있습니다.  
      operationId: getPosts
      parameters:
        - name: search
          in: query
          required: false
          description: 검색할 키워드
          schema:
            type: string
            examples: [spring]
      responses:
        '200':
          description: 채용 공고 목록 조회 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
    post:
      tags:
        - Post
      summary: 새로운 채용공고를 등록합니다.
      description: 회사가 채용공고를 등록할 수 있습니다.
      operationId: createPost
      requestBody:
        description: 회사의 채용공고 상세 내용을 입력합니다.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostDetails'
        required: true
      responses:
        '201':
          description: 채용공고 생성 완료
          headers:
            Location:
              description: 생성된 채용공고 조회 URL
              schema:
                type: string
                format: uri
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostDetails'
        '422':
          description: 유효성 검사에 통과하지 못한 경우
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemValidation'
  /posts/{id}:
    parameters:
      - name: id
        in: path
        description: 수정할 채용공고의 id
        required: true
        schema:
          type: integer
    patch:
      tags:
        - Post
      summary: 채용공고를 수정합니다.
      requestBody:
        description: 회사의 채용공고 상세 내용을 입력합니다.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostDetails'
        required: true
      responses:
        '200':
          description: 채용공고 수정 완료
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostDetails'
        '404':
          description: id와 일치하는 채용 공고를 찾을 수 없는 경우
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '422':
          description: 유효성 검사에 통과하지 못한 경우
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemValidation'
    delete:
      tags:
        - Post
      summary: 채용공고를 삭제합니다.
      responses:
        '204':
          description: 삭제 완료
          content:
            text/plain: 
              example: ''
        '404':
          description: id와 일치하는 채용 공고를 찾을 수 없는 경우
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
    get:
      tags:
        - Post
      summary: 채용공고 상세 내용을 조회합니다.
      responses:
        '200':
          description: 조회 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostDetails'
        '404':
          description: id와 일치하는 채용 공고를 찾을 수 없는 경우
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
  /applications:
    post:
      tags:
        - Application
      summary: 사용자가 채용공고에 지원합니다.
      description: 사용자가 채용공고에 지원합니다.
      operationId: createApplication
      requestBody:
        description: 사용자 식별자와 지원할 채용공고의 식별자를 작성합니다.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Application'
        required: true
      responses:
        '201':
          description: 지원 완료
          headers:
            Location:
              description: 생성된 지원내역 조회 URL
              schema:
                type: string
                format: uri
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Application'
        '404':
          description: id와 일치하는 채용공고 또는 사용자를 찾을 수 없는 경우
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Problem'
        '409':
          description: 이미 사용자가 채용공고에 지원하여 전형이 진행 중인 경우
          content:
            application/problem+json:
              schema:
                examples: [{"title": "지원한 채용공고", "status": 409, "details": ["해당 채용공고(id = {id})에는 이미 지원하여 전형이 진행중입니다."]}]
                $ref: '#/components/schemas/Problem'
components:
  schemas:
    Address:
      type: object
      properties:
        street:
          type: string
          examples: ['올림픽로 300, 롯데월드타워 35층']
        city:
          type: string
          examples: [송파구]
        state:
          type: string
          examples: [서울특별시]
    Application:
      type: object
      properties:
        postId:
          type: integer
          format: int64
          examples: [12]
        userId:
          type: integer
          format: int64
          examples: [42]
        appliedAt:
          type: string
          readOnly: true
          format: date-time
        updatedAt:
          type: string
          readOnly: true
          format: date-time
        status:
          type: string
          readOnly: true
          examples: [서류접수]
    CompanyInPost:
      type: object
      readOnly: true
      properties:
        id:
          type: integer
          format: int64
          examples: [1]
        name:
          type: string
          examples: [(주)원티드랩]
    Post:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
          format: int64
          examples: [77]
        company:
          $ref: '#/components/schemas/CompanyInPost'
        address:
          $ref: '#/components/schemas/Address'
        positionName:
          type: string
          examples: [백엔드 주니어 개발자]
        reward:
          type: integer
          format: int64
          examples: [1500000]
        skills:
          type: array
          items:
            $ref: '#/components/schemas/Skill'
    PostDetails:
      allOf:
        - $ref: '#/components/schemas/Post'
        - type: object
          properties:
            jobDescription:
              type: string
              examples: [원티드랩에서 백엔드 주니어 개발자를 채용합니다.]
            otherPostsByCompany:
              type: array
              readOnly: true
              items:
                type: integer
                format: int64
              examples: [[11, 23, 44, 64]]
    Skill:
      type: object
      properties:
        name:
          type: string
          examples: [Java]
    Problem: 
      type: object
      properties:
        title:
          type: string
          description: 오류 제목
          examples: [존재하지 않는 채용공고]
        status:
          type: integer
          description: HTTP status code
          examples: [404]
        details:
          type: array
          description: 오류에 대한 상세한 설명
          items:
            type: string
            examples: ['입력하신 채용공고의 id = {id} 는 존재하지 않습니다.']
    ProblemValidation: 
      type: object
      properties:
        title:
          type: string
          description: 오류 제목
          examples: [유효하지 않은 입력]
        status:
          type: integer
          description: HTTP status code
          examples: [422]
        details:
          type: array
          description: 오류에 대한 상세한 설명
          items:
            type: string
            examples: ["채용포지션(positionName) 또는 채용내용(jobDescription)이 작성되지 않았습니다. 확인해 주세요."]
